### ISSUE TITLE
Maybe a Bug

### ISSUE THREAD

**Issue by ZiyiLiubird** [inspirai/TimeChamber#1]
It occurred:

> NotADirectoryError: [Errno 20] Not a directory: '/home/lzy/lzy/MARL/self-play/TimeChamber/timechamber/models/ant_sumo/policy.pth/../elo.jpg'  

when I run policy evaluation:

`python train.py task=MA_Ant_Sumo test=True headless=True checkpoint='models/ant_sumo/policy.pth' `

Maybe this line code has some problem: TimeChamber/timechamber/learning/ppo_sp_player.py", line 286,

And the bug can be fixed by replacing

`plt.savefig(self.params['load_path'] + '/../elo.jpg')`

to

`parent_path = os.path.dirname(self.params['load_path'])`

`plt.savefig(os.path.join(parent_path, 'elo.jpg'))`

**Comment by ZiyiLiubird** [comment]
The second checkpoint path in "run testing for Ant Sumo policy" in ReadMe file should be "models/ant_sumo/policy.pth" instead of "models/ant_sumo".

**Comment by ZeldaHuang** [comment]
> It occurred:
> 
> > NotADirectoryError: [Errno 20] Not a directory: '/home/lzy/lzy/MARL/self-play/TimeChamber/timechamber/models/ant_sumo/policy.pth/../elo.jpg'
> 
> when I run policy evaluation:
> 
> `python train.py task=MA_Ant_Sumo test=True headless=True checkpoint='models/ant_sumo/policy.pth' `
> 
> Maybe this line code has some problem: TimeChamber/timechamber/learning/ppo_sp_player.py", line 286,
> 
> And the bug can be fixed by replacing
> 
> `plt.savefig(self.params['load_path'] + '/../elo.jpg')`
> 
> to
> 
> `parent_path = os.path.dirname(self.params['load_path'])`
> 
> `plt.savefig(os.path.join(parent_path, 'elo.jpg'))`

Thanks,I fixed it.

**Comment by ZeldaHuang** [comment]
> Perhaps the second checkpoint path in "run testing for Ant Sumo policy" in ReadMe file should be "models/ant_sumo/policy.pth" instead of "models/ant_sumo".

 `checkpoint="models/ant_sumo"` means we can load all policies in "models/ant_sumo" and evalute their ELO rating.

**Comment by ZiyiLiubird** [comment]
> > Perhaps the second checkpoint path in "run testing for Ant Sumo policy" in ReadMe file should be "models/ant_sumo/policy.pth" instead of "models/ant_sumo".
> 
> `checkpoint="models/ant_sumo"` means we can load all policies in "models/ant_sumo" and evalute their ELO rating.

However, the program raises error

> Exception invalid load key, '\xff'. when trying to execute <function load at 0x7fb89812f790> with args:('/home/lzy/lzy/MARL/self-play/TimeChamber/timechamber/models/ant_sumo/elo.jpg',) and kwargs:{'map_location': device(type='cuda', index=0)}...
RuntimeError: Could not execute <function load at 0x7fb89812f790>, give up after 5 attempts...

when I use the command "python train.py task=MA_Ant_Sumo test=True headless=True checkpoint='models/ant_sumo' player_pool_type=vectorized".

**Comment by floodsung** [comment]
We only provide one trained model for evaluation, you'd better train from scratch and save several policies for elo evaluation.

**Comment by ZeldaHuang** [comment]
> .pth files
I add some judgements make sure only load ".pth" files.
