### ISSUE TITLE
How much time costs on training?

### ISSUE THREAD

**Issue by ameliacode** [inspirai/TimeChamber#10]
In Humanoid strike task config training file, it seems that epoch has to reach until 100000, which I assume, may take about 10days or more..
Could you give the specfic training days for this?

**Comment by ZiyiLiubird** [comment]
We spent 12~14 days training Humanoid strike using one 4090 GPU for 50000 epochs. In fact, ~2000 epochs agents can get meaningful strategies, and diverse strategies may emerge with more epochs.

**Comment by ameliacode** [comment]
I did run from the scratch, but I don't think 2000epochs get good result :(. 
I found that the agents just start learning to face themselves and get closer to each other in epoch 2000.

Oh before I close this issue, may I know the best reward value in strike task?

Thanks in advance

**Comment by ZiyiLiubird** [comment]
The reward value is not very meaningful because in zero-sum games agents may find some weird strategies to get rewards as much as possible.  In my mind, the agent can learn the skill that falling down his opponents after ~10000 epochs with ~15000 rewards.
