### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ZiyiLiubird** [inspirai/TimeChamber#2]
https://github.com/inspirai/TimeChamber/blob/f63b0404631f4ec9ab34e5084fde6b3a88fd4c6a/timechamber/learning/ppo_sp_agent.py#L57

https://github.com/inspirai/TimeChamber/blob/f63b0404631f4ec9ab34e5084fde6b3a88fd4c6a/timechamber/learning/ppo_sp_agent.py#L58

https://github.com/inspirai/TimeChamber/blob/f63b0404631f4ec9ab34e5084fde6b3a88fd4c6a/timechamber/learning/ppo_sp_agent.py#L60

https://github.com/inspirai/TimeChamber/blob/f63b0404631f4ec9ab34e5084fde6b3a88fd4c6a/timechamber/learning/ppo_sp_agent.py#L61

Maybe line 58, and 59 should exchange with line 61, and 62 ?

**Comment by ZeldaHuang** [comment]
> Maybe line 58, and 59 should exchange with line 61, and 62 ?

Yes, acutally these two player_pool_type are not well tested, so I deprecated  them in [commit](https://github.com/inspirai/TimeChamber/commit/37c2b40b8306921b748b318828769abafb90f347)
