### ISSUE TITLE
how to reproduce the README demo

### ISSUE THREAD

**Issue by Jackory** [inspirai/TimeChamber#3]
I want to see the video of policy evaluation, so I set `headless=False`. But I found that the code run very slow in https://github.com/Jackory/TimeChamber/blob/37c2b40b8306921b748b318828769abafb90f347/timechamber/tasks/ma_ant_sumo.py#L63.
Could you give me some instructions to reproduce the README demo?  Thanks

**Comment by ZiyiLiubird** [comment]
> I want to see the video of policy evaluation, so I set `headless=False`. But I found that the code run very slow in https://github.com/Jackory/TimeChamber/blob/37c2b40b8306921b748b318828769abafb90f347/timechamber/tasks/ma_ant_sumo.py#L63. Could you give me some instructions to reproduce the README demo? Thanks

You can set num_envs=2, e.g., 

`python train.py task=MA_Ant_Sumo test=True headless=False checkpoint='models/ant_sumo/policy.pth' num_envs=2`

**Comment by Jackory** [comment]
That's fine. Thanks! But I found another problem that  `MA_VEC_TASK`  didn't support `gym.wrappers.RecordVideo`. When I set `capture_video=True`, no video was recorded. Therefore, it didn't support wandb to record videos of training we can watch online.

**Comment by ZeldaHuang** [comment]
Support capture video in [commit](https://github.com/inspirai/TimeChamber/commit/dd461050a9db06cc3f506fac26751867b1f0b775).

**Comment by Jackory** [comment]
It works, thanks!
