### ISSUE TITLE
ModuleNotFoundError: No module named 'timechamber.ase'

### ISSUE THREAD

**Issue by xjturobocon** [inspirai/TimeChamber#4]
when I run the code, there is an error:
`Traceback (most recent call last):
  File "train.py", line 47, in <module>
    from timechamber.ase import ase_agent
ModuleNotFoundError: No module named 'timechamber.ase'
`
I find that there is not 'ase' directory  in timechamber, how can i get ase?

**Comment by ZiyiLiubird** [comment]
We have updated the repository, and we are sorry for our negligence. please re-download the codes and run it again.
