### ISSUE TITLE
Suggestion to use RNN for multi-agent tasks

### ISSUE THREAD

**Issue by jacktheripper19** [inspirai/TimeChamber#6]
Hello,
Good job for the amazing work. I noticed that for the task of ma humanoid strike, you used a similar reward design to the one used for boxing agents in this paper:

https://dl.acm.org/doi/abs/10.1145/3450626.3459761

I was thinking that maybe strategic behavior could emerge with the sword fighters and the results could be better if you add a memory module (lstm, gru, transformer) like in the paper. Also, as far as I understand, in the literature of multi-agent partially observable mdp, each agent should take the history of its observations when taking actions to have more accurate belief about the global state and also to account for the non-stationary environment.

Thanks

**Comment by ZiyiLiubird** [comment]
Hi, thanks for your suggestions. In fact, the observation of the Humanoid Strike agent contains information about his opponent, so it can be viewed as a nearly fully observable MDP. I will add an optional memory module later. If you have more suggestions about the reward design, welcome open a PR!
