### ISSUE TITLE
As configured. Strike is only using 50% of my GPU

### ISSUE THREAD

**Issue by Robokan** [inspirai/TimeChamber#8]
I have a rtx 4090 and when I use watch-smi and train Strike it uses less than half the memory and only 50% of the the GPU. How can I change the settings to use the rest of the GPU?

**Comment by Robokan** [comment]
double the number of environments does increase memory usage and % but not by very much. Wonder how I go about really maximizing GPU usage.

**Comment by ZeldaHuang** [comment]
have you tried to increase the batch_size in rl_games config?

**Comment by Robokan** [comment]
Thanks, I will try that.
